version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: next
    versions:
    - 10.0.7
  - dependency-name: husky
    versions:
    - 5.1.1
